spring:
  data:
    mongodb:
      host: 47.95.254.253
      port: 27017
      uri: mongodb://cat2018:cat2018@${spring.data.mongodb.host}:${spring.data.mongodb.port}/cat
  redis:
    host: 47.95.254.253
    database: 1
    password: cat2018
server:
  port: 80

token:
  auth: false

wx:
  app-id: ${WX_APP_ID:wxdb76539383687ef1}
  app-secret: ${WX_APP_SECRET:3e680441efa752ba711e688766e3bc6f}
  mch-id: ${WX_MCH_ID:}
  mch-key: ${WX_MCH_KEY:}
  notify-url: ${WX_NOTIFY_URL:}